### ISSUE TITLE
Unknown Save format 

### ISSUE THREAD

**Issue by chaosrunner** [zarroboogs/p5spc.saveutil#5]
Running the following command:
```p5spc.saveutil.exe convert --input savedata --target PC```
results in ```Unknown save format, aborting...```. I am trying to convert a switch save(EN) to PC and have this issue.
I had dumped the switch save with checkpoint and JKSV so I am not sure whats the issue
The game version is 1.0.0

**Comment by yuukiw** [comment]
you have to specify the input path. --input <path here> --target

**Comment by chaosrunner** [comment]
By using absolute paths? I have specified the location with the absolute path and results in the same error and  I don't think it would matter If i specified the file path or not since p5spc and my save data were in the same location. I moved the file locations and attempted to add the absolute path for the input but still get the same error. 
![image](https://user-images.githubusercontent.com/24767759/109790060-f814c900-7bde-11eb-8c64-d873f5dc16a1.png)

**Comment by yuukiw** [comment]
Add the file extension. Also the save file must be decrypted first.

**Comment by chaosrunner** [comment]
How would I go about decrypting the switch save? I thought that the saves are automatically decrypted when exporting them, also the save does not have a file Extention.

**Comment by yuukiw** [comment]
Ah then you dont need to decrypt the file. Try to add the extention.

**Comment by chaosrunner** [comment]
Still, no dice, would you mind converting my save for me, It might be an issue on my end not too sure.

[savedata.zip](https://github.com/zarroboogs/p5spc.saveutil/files/6076723/savedata.zip)

**Comment by zarroboogs** [comment]
Try v1.2.0: <https://github.com/zarroboogs/p5spc.saveutil/releases/tag/v1.2.0>

**Comment by chaosrunner** [comment]
Thank you, It works like a charm
